# Generated by Django 3.1.3 on 2022-06-28 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_auto_20220628_0722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='lesson_id',
            new_name='lesson',
        ),
    ]
